In [1]:
 import numpy as np

np.array([1, 2, 3]) 
# array([1, 2, 3])

array([1, 2, 3])

In [15]:
np.array([1.1, 2.1, 3.12])

array([1.1 , 2.1 , 3.12])

In [8]:
print(np.array([1, 2, 3], dtype=complex))

[1.+0.j 2.+0.j 3.+0.j]


In [22]:
np.array({0:123, 1: 456})
# array({0: 123, 1: 456})

array({0: 123, 1: 456}, dtype=object)

In [36]:
np.array(list({0: 123, 1: 456}.items()))
# array([[  0 123]  [  1 456]])

array([[  0, 123],
       [  1, 456]])

In [24]:
np.zeros((2, 3))
# 建立由 0 組成的 2x3 陣列

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.ones((2, 3))
# 建立由 1 組成的 2x3 陣列

array([[1., 1., 1.],
       [1., 1., 1.]])

In [26]:
np.full((2, 3), 9)
# 建立由 9 組成的 2x3 陣列

array([[9, 9, 9],
       [9, 9, 9]])

In [27]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.empty((3, 3))

array([[-1.72723371e-077, -1.72723371e-077,  2.96439388e-323],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000],
       [-1.72723371e-077, -1.72723371e-077,  6.48224638e+170]])

In [30]:
np.empty((2, 3))

array([[1.72723371e-077, 1.72723371e-077, 2.96439388e-323],
       [1.72723371e-077, 1.72723371e-077, 6.48224638e+170]])

In [31]:
np.arange( 10, 30, 5 )
# array([10, 15, 20, 25])

array([10, 15, 20, 25])

In [46]:
np.linspace( 0, 2, 4 )
# array([0. 1. 2.])

array([0.        , 0.66666667, 1.33333333, 2.        ])

In [52]:
np.logspace( 0, 3, 4 )
# array([1. 10. 100.])

array([   1.,   10.,  100., 1000.])

In [40]:
from numpy.random import default_rng
rng = default_rng()

normal = rng.standard_normal((3,2))
normal

array([[-0.73177093,  0.28068802],
       [-0.61522045, -1.4648072 ],
       [ 0.51217457, -2.29225885]])

In [41]:
random = rng.random((3,2))
random

array([[0.29202008, 0.59824189],
       [0.24296946, 0.5684791 ],
       [0.65905072, 0.34021731]])

In [60]:
integers = rng.integers(0, 10, size=(3,2))
integers

array([[5, 1],
       [1, 5],
       [4, 6]])

In [65]:
c = np.zeros(3, dtype=dt)

In [67]:
name = ['Chloe', 'Charlotte', 'Clara']
num_1 = [11, 12, 13]
num_2 = [14, 15, 16]
check = ['Y', 'Y', 'N']

c['Name'] = name
c['num1'] = num_1
c['num2'] = num_2
c['True'] = check

print(c)

[('Chloe', 11, 14, 'Y') ('Charl', 12, 15, 'Y') ('Clara', 13, 16, 'N')]


In [71]:
c['Name']

array(['Chloe', 'Charl', 'Clara'], dtype='<U5')

In [72]:
c[0]

('Chloe', 11, 14, 'Y')

In [76]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
1.18.1


In [77]:
# 內建型態做轉換

import numpy as np

np.array([1, 2, 3])

array([1, 2, 3])

In [78]:
# 會自動轉換成範圍比較大的型態：

print(np.array([1, 2, 3.0]), np.array([1, 2, 3.0]).dtype)

[1. 2. 3.] float64


In [79]:
# 也可以指定成想要的型態：

print(np.array([1, 2, 3], dtype=complex), np.array([1, 2, 3], dtype=complex).dtype)

[1.+0.j 2.+0.j 3.+0.j] complex128


In [80]:
# 字典型態被轉成陣列不符合期待

print(np.array({0: 123, 1: 456}))
print(np.array({0: 123, 1: 456}).size)

{0: 123, 1: 456}
1


In [81]:
# 正確的寫法應該寫轉成有序的 List 再作轉換

print(np.array(list({0: 123, 1: 456}.items())))
print(np.array(list({0: 123, 1: 456}.items())).size)

[[  0 123]
 [  1 456]]
4


In [82]:
# 從固定大小的初始值開始

print(np.zeros((2, 3)))
print(np.ones((2, 3)))
print(np.full((2, 3), 9))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[9 9 9]
 [9 9 9]]


In [83]:
# np.zeros 和 np.empty 

print(np.zeros((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


In [84]:
# 從固定大小的序列值開始

print(np.arange( 10, 30, 5 ))
print(np.linspace( 0, 2, 3 ))
print(np.logspace( 0, 2, 3 ))

[10 15 20 25]
[0. 1. 2.]
[  1.  10. 100.]


In [85]:
## 從固定大小的亂數值開始（新版）

from numpy.random import default_rng
rng = default_rng()

normal = rng.standard_normal((3,2))
random = rng.random((3,2))
integers = rng.integers(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

[[ 0.33120611 -0.9405642 ]
 [-1.46119822  0.02795958]
 [ 0.78866389 -2.49768717]]
[[0.14862245 0.00175751]
 [0.31803642 0.82241052]
 [0.73943062 0.31160414]]
[[3 6]
 [4 6]
 [9 5]]


In [86]:
## 從固定大小的亂數值開始（舊版）

normal = np.random.randn(2, 3)
random = np.random.random((3,2))
integers = np.random.randint(0, 10, size=(3,2))

print(normal)
print(random)
print(integers)

[[-0.96317372  0.56396977 -0.17099692]
 [ 0.85069298 -1.26186843 -0.06733582]]
[[0.95273157 0.73306163]
 [0.91018691 0.43807833]
 [0.54183026 0.55908306]]
[[2 0]
 [2 5]
 [3 8]]


In [89]:
import numpy as np

In [ ]:
# %load structured.txt
Jay,1,2,Yes,87%
James,3,4,No,3%
Joe,5,6,Yes,55%

In [92]:
# 使用字母代表的資料型別
dt = np.dtype('U5, i8, i8, U3')

In [93]:
a = np.genfromtxt("structured.txt", delimiter=',', dtype=dt)
a

array([('Jay', 1, 2, 'Yes'), ('James', 3, 4, 'No'), ('Joe', 5, 6, 'Yes')],
      dtype=[('f0', '<U5'), ('f1', '<i8'), ('f2', '<i8'), ('f3', '<U3')])

In [94]:
dt = np.dtype({'names':('Name', 'num1', 'num2', 'True'), 'formats':((np.str_, 5), np.int32, int, 'U3')})

In [95]:
b = np.genfromtxt("structured.txt", delimiter=',', dtype=dt)
b

array([('Jay', 1, 2, 'Yes'), ('James', 3, 4, 'No'), ('Joe', 5, 6, 'Yes')],
      dtype=[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i8'), ('True', '<U3')])

In [96]:
b[0]

('Jay', 1, 2, 'Yes')

In [97]:
b['Name']

array(['Jay', 'James', 'Joe'], dtype='<U5')

In [98]:
b[1]['True']

'No'

In [99]:
b[b['num2'] >= 3]['Name']

array(['James', 'Joe'], dtype='<U5')

In [100]:
c = np.zeros(3, dtype=dt)
c

array([('', 0, 0, ''), ('', 0, 0, ''), ('', 0, 0, '')],
      dtype=[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i8'), ('True', '<U3')])

In [101]:
print(c.dtype)

[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i8'), ('True', '<U3')]


In [102]:
name = ['Chloe', 'Charlotte', 'Clara']
num_1 = [11, 12, 13]
num_2 = [14, 15, 16]
check = ['Y', 'Y', 'N']

In [103]:
c['Name'] = name
c['num1'] = num_1
c['num2'] = num_2
c['True'] = check

In [104]:
print(c)

[('Chloe', 11, 14, 'Y') ('Charl', 12, 15, 'Y') ('Clara', 13, 16, 'N')]


In [105]:
c_rec = c.view(np.recarray)
c_rec

rec.array([('Chloe', 11, 14, 'Y'), ('Charl', 12, 15, 'Y'),
           ('Clara', 13, 16, 'N')],
          dtype=[('Name', '<U5'), ('num1', '<i4'), ('num2', '<i8'), ('True', '<U3')])

In [106]:
c_rec.Name

array(['Chloe', 'Charl', 'Clara'], dtype='<U5')

In [1]:
import numpy as np 

In [2]:
name_list = ['小明','小華','小菁','小美','小張','John','Mark','Tom']
sex_list = ['boy','boy','girl','girl','boy','boy','boy','boy']
weight_list = [67.5,75.3,50.1,45.5,80.8,90.4,78.4,70.7]
rank_list = [8,1,5,4,7,6,2,3]
myopia_list = [True,True,False,False,True,True,False,False]

#1. 將上列list依照['name', 'sex', 'weight', 'rank', 'myopia']順序擺入array，並且資料型態順序擺入[Unicode,Unicode,float,int,boolean]

#2. 呈上題，將array中體重(weight)數據集取出算出全部平均體重

#3. 呈上題，進一步算出男生(sex欄位是boy)平均體重、女生(sex欄位是girl)平均體重

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

In [4]:
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [5]:
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。

3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。