In [1]:
import numpy as np 

a = np.arange(6)
print(a)
# [0 1 2 3 4 5]

print(a.sum()) # 15
print(a.min()) # 0
print(a.max()) # 5

[0 1 2 3 4 5]
15
0
5


In [2]:
import numpy as np 

a = np.arange(6)

print(a.sum()) # 15
print(np.sum(a)) # 15
print(sum(a)) # 15

15
15
15


In [3]:
import numpy as np 

b = np.arange(12).reshape(3, 4)
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

In [4]:
print(b.sum())
# 66

print(b.sum(axis=0))
# array([12, 15, 18, 21])

print(b.sum(axis=1))
# array([0, 4, 8])

66
[12 15 18 21]
[ 6 22 38]


In [8]:
import numpy as np 

a = np.array([1, 3, 2, 5, 4])
print(a.sort())
# None
print(a)
# [1 2 3 4 5]

None
[1 2 3 4 5]


In [6]:
import numpy as np 

a = np.array([1, 3, 2, 5, 4])
print(np.sort(a))
# [1 2 3 4 5]
print(a)
# [1 3 2 5 4]

[1 2 3 4 5]
[1 3 2 5 4]


In [23]:
import numpy as np 

a = np.array([1, 9, 36, 25, 4])

In [24]:
a.quicksort(axis=-1, kind=None)

AttributeError: 'numpy.ndarray' object has no attribute 'quicksort'

In [25]:
a

array([ 1,  9, 36, 25,  4])

In [26]:
import numpy as np 

np.searchsorted([1,2,3,4,5], 3)
# 2

2

In [32]:
import numpy as np 

np.searchsorted(
    [1, 2, 3, 4, 5],
    1
)
# [0, 5, 2, 4]

0

In [33]:
import numpy as np 

a = np.arange(6)
# [0, 1, 2, 3, 4, 5]

print(a.reshape(3, 2))
# [[0 1]
#  [2 3]
#  [4 5]]
print(a)
# [0, 1, 2, 3, 4, 5]

[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


In [34]:
import numpy as np 

a = np.arange(6)
# [0, 1, 2, 3, 4, 5]

print(a.resize((3, 2)))
# None
print(a)
# [[0 1]
#  [2 3]
#  [4 5]]

None
[[0 1]
 [2 3]
 [4 5]]


In [35]:
import numpy as np 

a = np.arange(6).reshape((3, 2))

print(a.ravel() )
print(a.flatten())
print(a.flat)

[0 1 2 3 4 5]
[0 1 2 3 4 5]


In [36]:
# 載入 NumPy 套件
import numpy as np

# 檢查正確載入與版本
print(np)
print(np.__version__)

<module 'numpy' from '/opt/anaconda3/lib/python3.7/site-packages/numpy/__init__.py'>
1.18.1


In [37]:
# 陣列中的統計方法


a = np.arange(6)
print(a)

print(a.sum()) 
print(a.min()) 
print(a.max()) 

[0 1 2 3 4 5]
15
0
5


In [38]:
# 一種功能，三種函式


a = np.arange(6)

print(a.sum()) 
print(np.sum(a))
print(sum(a)) 

15
15
15


In [39]:
# 陣列中的軸參數

b = np.arange(12).reshape(3, 4)

print(b)
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
66
[12 15 18 21]
[ 6 22 38]


In [40]:
# 搜尋與排序方法

import numpy as np 

a = np.array([1, 3, 2, 5, 4])
print(a.sort())
print(a)

None
[1 2 3 4 5]


In [43]:
import numpy as np 

a = np.array([1, 3, 2, 5, 4])
print(np.sort(a))
print(a)

[1 2 3 4 5]
[1 3 2 5 4]


In [44]:
import numpy as np 

print(np.searchsorted([1,2,3,4,5], 3))
print(np.searchsorted(
    [1, 2, 3, 4, 5],
    [-10, 10, 3, 5]
))

2
[0 5 2 4]


In [45]:
# reshape 和 resize

import numpy as np 

a = np.arange(6)

print(a)
print(a.reshape(3, 2))
print(a)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


In [46]:
import numpy as np 

a = np.arange(6)

print(a)
print(a.resize((3, 2)))
print(a)

[0 1 2 3 4 5]
None
[[0 1]
 [2 3]
 [4 5]]


In [47]:
# 三種陣列攤平用法

import numpy as np 

a = np.arange(6).reshape((3, 2))

print(a.ravel() )
print(a.flatten())
print(a.flat)
print(list(a.flat))

[0 1 2 3 4 5]
[0 1 2 3 4 5]
[0, 1, 2, 3, 4, 5]


1. [簡答題] 請問下列這三種方法有什麼不同？

In [48]:
# 一種功能，三種函式


a = np.arange(6)

print(a.sum()) 
print(np.sum(a))
print(sum(a)) 

15
15
15


2. 請對一個 5x5 的隨機矩陣作正規化的操作。

In [50]:
A = np.random.random((5, 5))
A

array([[0.45805531, 0.78714595, 0.71668793, 0.5346536 , 0.40957916],
       [0.68777877, 0.52762101, 0.14666117, 0.45769234, 0.69756155],
       [0.63059905, 0.06588789, 0.89052058, 0.5782891 , 0.97364122],
       [0.14151697, 0.32453718, 0.33273985, 0.24000276, 0.50414282],
       [0.88922772, 0.99517063, 0.30584915, 0.01857382, 0.91403047]])

In [52]:
A = (A - A.min()) / (A.max() - A.min())
A

array([[0.45001323, 0.78699021, 0.71484374, 0.52844712, 0.4003754 ],
       [0.68524179, 0.52124601, 0.13115684, 0.44964157, 0.695259  ],
       [0.62669181, 0.04844791, 0.89284212, 0.57312831, 0.97795466],
       [0.12588937, 0.31329548, 0.32169471, 0.22673527, 0.49720518],
       [0.89151826, 1.        , 0.29415961, 0.        , 0.91691539]])

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。

In [51]:
np.random.seed(6)
B = np.array(np.random.randint(1, 100, 10))
B[np.argmax(B)] = -1
print(B)

[11 74 -1 80 81 63 26  2 76 78]


Part.2-1-02 NumPy 陣列進階操作

In [59]:
import numpy as np

1. NumPy 陣列重塑

In [60]:
a = np.array([[ 0,  1,  2,  3], 
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [61]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [62]:
b = a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [63]:
b[3] = 100
b

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [64]:
a

array([[  0,   1,   2, 100],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [65]:
a.ravel(order='C')

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [66]:
a.ravel(order='F')

array([  0,   4,   8,   1,   5,   9,   2,   6,  10, 100,   7,  11])

In [67]:
a = np.arange(15)

In [68]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [69]:
a.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [70]:
a.size

15

In [71]:
a.reshape((3, 6))

ValueError: cannot reshape array of size 15 into shape (3,6)

In [72]:
a.reshape((5, -1))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [73]:
b = a.reshape((3, 5))
b[0, 2] = 100
b

array([[  0,   1, 100,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [74]:
a

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [75]:
b = np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [76]:
b.size

15

In [77]:
b.resize((3, 6), refcheck=False)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14,  0,  0,  0]])

In [78]:
b.resize(3, refcheck=False)
b

array([0, 1, 2])

2. 軸 (axis) 與維度 (dimension)

In [79]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [80]:
a = np.arange(6).reshape(3, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [95]:
a = np.array([[[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]],
              [[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [96]:
a.shape

(2, 4, 3)

In [98]:
a.sum(axis=2)

array([[ 6, 15, 24, 33],
       [ 6, 15, 24, 33]])

In [84]:
a = np.arange(12).reshape(2, 6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [85]:
a[:,np.newaxis,:].shape

(2, 1, 6)

In [86]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

3. NumPy 陣列的合併與分割

In [100]:
a = np.arange(10).reshape(5, 2)
b = np.arange(6).reshape(3, 2)

In [101]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [102]:
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [103]:
np.concatenate((a, b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

In [104]:
# stack() 範例
c = np.arange(10).reshape(5, 2)
np.stack((a, c), axis=1)

array([[[0, 1],
        [0, 1]],

       [[2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5]],

       [[6, 7],
        [6, 7]],

       [[8, 9],
        [8, 9]]])

In [105]:
# hstack() 範例
np.hstack((a, c))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [106]:
# vstack() 範例
np.vstack((a, b))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

In [107]:
a = np.arange(10).reshape(5, 2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [109]:
# 依 axis 0 等分 split
np.split(a, 5)

[array([[0, 1]]),
 array([[2, 3]]),
 array([[4, 5]]),
 array([[6, 7]]),
 array([[8, 9]])]

In [110]:
# split 為 (2,2), (1,2), (2,2) 三個陣列，並回傳含 3 個陣列的 List
np.split(a, [2,3])

[array([[0, 1],
        [2, 3]]),
 array([[4, 5]]),
 array([[6, 7],
        [8, 9]])]

In [111]:
b = np.arange(30).reshape(5, 6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [112]:
# 依水平軸去做等分分割
np.hsplit(b, 3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29]])]

In [113]:
# 依水平軸照區段去分割
np.hsplit(b, [2, 3, 5])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2],
        [ 8],
        [14],
        [20],
        [26]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29]])]

In [114]:
# 依垂直軸按照區段去分割，超出的區段則傳回空陣列
np.vsplit(b, [2, 4, 6])

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]]),
 array([], shape=(0, 6), dtype=int64)]

4. 迭代

In [115]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [116]:
for i in a:
    print(i)

0
1
2
3
4


In [117]:
b = np.arange(6).reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [118]:
for row in b:
    print(row)

[0 1 2]
[3 4 5]


In [119]:
for i in b.flat:
    print(i)

0
1
2
3
4
5


5. 搜尋與排序

In [121]:
a = np.random.randint(1, 20, 10)
a

array([ 2, 13, 19,  5,  2, 16,  6, 16,  7,  2])

In [122]:
# 陣列中最大的元素值
np.amax(a)

19

In [123]:
# 陣列中最小的元素值
np.amin(a)

2

In [124]:
b = a.reshape(2, 5)
b

array([[ 2, 13, 19,  5,  2],
       [16,  6, 16,  7,  2]])

In [125]:
# 若設定 keepdims=True，結果會保留原陣列的維度來顯示。
np.amax(b, keepdims=True)

array([[19]])

In [126]:
# 列出各 row 最大值
b.max(axis=1)

array([19, 16])

In [127]:
# 同樣的 amax 也可以依軸列出各 row 最大值
np.amax(b, axis=1)

array([19, 16])

In [128]:
# 列出各 column 最小值
b.min(axis=0)

array([ 2,  6, 16,  5,  2])

In [131]:
np.random.seed(0)
a = np.random.randint(1, 20, size=(3, 4))
a

array([[13, 16,  1,  4],
       [ 4,  8, 10, 19],
       [ 5,  7, 13,  2]])

In [132]:
np.argmax(a)

7

In [133]:
# 列出各 column 的最大值索引, 分別為 [0, 0, 2, 1]
np.argmax(a, axis=0)

array([0, 0, 2, 1])

In [134]:
# 元素值 1 為最小值，展平後的索引值為 2。
a.argmin()

2

In [136]:
a

array([[13, 16,  1,  4],
       [ 4,  8, 10, 19],
       [ 5,  7, 13,  2]])

In [137]:
np.where(a > 10)

(array([0, 0, 1, 2]), array([0, 1, 3, 2]))

In [143]:
np.where(a > 10, "Y", "N")

array([['N', 'N'],
       ['N', 'N'],
       ['N', 'N'],
       ['N', 'N'],
       ['N', 'N']], dtype='<U1')

In [144]:
np.random.seed(2)
a = np.random.randint(0, 5, 10)
a

array([0, 0, 3, 2, 3, 0, 2, 1, 3, 2])

In [145]:
np.nonzero(a)

(array([2, 3, 4, 6, 7, 8, 9]),)

In [146]:
a.nonzero()

(array([2, 3, 4, 6, 7, 8, 9]),)

In [147]:
np.random.seed(3)
a = np.random.randint(0, 20, 10)
a

array([10,  3,  8,  0, 19, 10, 11,  9, 10,  6])

In [148]:
np.sort(a)

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19])

In [149]:
a.argsort()

array([3, 1, 9, 2, 7, 0, 5, 8, 6, 4])

In [150]:
a.sort()
a

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19])

In [151]:
b = np.random.randint(0, 20, size=(5, 4))
b

array([[ 0, 12,  7, 14],
       [17,  2,  2,  1],
       [19,  5,  8, 14],
       [ 1, 10,  7, 11],
       [ 1, 15, 16,  5]])

In [152]:
np.sort(b, axis=0)

array([[ 0,  2,  2,  1],
       [ 1,  5,  7,  5],
       [ 1, 10,  7, 11],
       [17, 12,  8, 14],
       [19, 15, 16, 14]])

In [153]:
c = np.random.randint(0, 100000000, 1000000)
np.sort(c, kind='heapsort')

array([      64,       96,      310, ..., 99999479, 99999561, 99999830])

1.將下列陣列(array1)，轉成維度為(5X6)的array，順序按列填充。(hint:order="F")

In [155]:
import numpy as np

#1. 將下兩列array存成npz檔
array1 = np.array(range(30))
array2 = np.array([2,3,5])
with open("old_array.npz", 'wb') as f:
    np.savez(f, array1, array2)

In [157]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [156]:
#2. 讀取剛剛的npz檔，加入下列array一起存成新的npz檔
array3 = np.array([[4,5,6],[1,2,3]])

old_array = np.load("old_array.npz")

with open("New_array.npz", 'wb') as f:
    np.savez(f, old_array['arr_0'], old_array['arr_1'], array3)
    
# 驗證答案
temp_array = np.load("New_array.npz")
temp_array.files
print(temp_array['arr_0'])
print(temp_array['arr_1'])
print(temp_array['arr_2'])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[2 3 5]
[[4 5 6]
 [1 2 3]]
