In [1]:
import pandas as pd

df1 = pd.DataFrame([[1, 2, 3]])
df2 = pd.DataFrame([[1, 1, 1]])

print(df1 + df2)
#     0  1  2
# 0  2  3  4

   0  1  2
0  2  3  4


In [2]:
import pandas as pd

df1 = pd.DataFrame([[1, 2, 3]], columns=['a', 'b', 'c'])
df2 = pd.DataFrame([[1, 1, 1]], columns=['c', 'd', 'e'])

print(df1 + df2)
#        a       b      c     d       e
# 0 NaN NaN     4 NaN NaN

    a   b  c   d   e
0 NaN NaN  4 NaN NaN


In [3]:
import pandas as pd

df1 = pd.DataFrame([[1, 2, 3]])

print(df1 + 1)
#    0  1  2
# 0  2  3  4

   0  1  2
0  2  3  4


In [4]:
import pandas as pd

df = pd.DataFrame([[1, 2, 3]])

print(df + 1)
#    0  1  2
# 0  2  3  4
print(df + pd.DataFrame([1]))
#    0   1   2
# 0  2 NaN NaN

   0  1  2
0  2  3  4
   0   1   2
0  2 NaN NaN


In [8]:
import numpy as np

a = np.array([1, 2, 3])

print(a + 1)
# [[2 3 4]]

print(a + np.array([1]))
# [[2 3 4]]

[2 3 4]
[2 3 4]


In [11]:
print(df > 2)
#        A      B     C
# a  False  False  True
# b   True   True  True

print(df[df > 2])
#      A    B  C
# a  NaN  NaN  3
# b  4.0  5.0  6

       0      1     2
0  False  False  True
    0   1  2
0 NaN NaN  3


In [18]:
print(df['A'] > 2)
# a    False
# b     True
# Name: A, dtype: bool

print(df[df['A'] > 2])
#    A  B  C
# b  4  5  6

KeyError: 'A'

In [33]:
import pandas as pd
df1 = pd.DataFrame([[1, 2, 3]], columns=['a', 'b', 'c'])
df1
print(df1['a'] > 2)


0    False
Name: a, dtype: bool


In [15]:
print(df['A'] > 2)
# a    False
# b     True
# Name: A, dtype: bool



KeyError: 'A'

In [35]:
import pandas as pd

df = pd.DataFrame({
    'col1': ['A', 'a', 'B', 'b'],
    'col2': [2, 1, 9, 8],
})

In [36]:
df

col1  col2
0    A     2
1    a     1
2    B     9
3    b     8

In [37]:
df.sort_values(by=['col1'])

col1  col2
0    A     2
2    B     9
1    a     1
3    b     8

In [38]:
df.sort_values(by=['col1', 'col2'])

col1  col2
0    A     2
2    B     9
1    a     1
3    b     8

In [39]:
df.sort_values(by='col2', ascending=False)

col1  col2
2    B     9
3    b     8
0    A     2
1    a     1

In [52]:
import pandas as pd

In [53]:
data = {
    'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 'cat', 'snake', 'cat', 'dog', 'dog'],
    'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
    'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'priority': ['yes', 'yes', 'no', 'yes', 'no', 'no', 'no', 'yes', 'no', 'no']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
df = pd.DataFrame(data, index=labels)
df

animal  age  visits priority
a    cat  2.5       1      yes
b    cat  3.0       3      yes
c  snake  0.5       2       no
d    dog  NaN       3      yes
e    dog  5.0       2       no
f    cat  2.0       3       no
g  snake  4.5       1       no
h    cat  NaN       1      yes
i    dog  7.0       2       no
j    dog  3.0       1       no

In [54]:
df['age'].mean()

3.4375

In [55]:
df.corr()

age    visits
age     1.000000 -0.133218
visits -0.133218  1.000000

In [44]:
df.sort_values(by=['age'])

animal  age  visits priority
c  snake  0.5       2       no
f    cat  2.0       3       no
a    cat  2.5       1      yes
b    cat  3.0       3      yes
j    dog  3.0       1       no
g  snake  4.5       1       no
e    dog  5.0       2       no
i    dog  7.0       2       no
d    dog  NaN       3      yes
h    cat  NaN       1      yes

In [45]:
df.sort_values(by=['visits'], ascending=False)

animal  age  visits priority
b    cat  3.0       3      yes
d    dog  NaN       3      yes
f    cat  2.0       3       no
c  snake  0.5       2       no
e    dog  5.0       2       no
i    dog  7.0       2       no
a    cat  2.5       1      yes
g  snake  4.5       1       no
h    cat  NaN       1      yes
j    dog  3.0       1       no

In [46]:
df['priority'] = df['priority'].apply(lambda x: 'True' if x=='yes' else 'False')

In [48]:
df

animal  age  visits priority
a    cat  2.5       1     True
b    cat  3.0       3     True
c  snake  0.5       2    False
d    dog  NaN       3     True
e    dog  5.0       2    False
f    cat  2.0       3    False
g  snake  4.5       1    False
h    cat  NaN       1     True
i    dog  7.0       2    False
j    dog  3.0       1    False

2. 一個包含兩個欄位的 DataFrame，將每個數字減去

In [57]:
df = pd.DataFrame(np.random.random(size=(5, 3)))
df

0         1         2
0  0.844970  0.993239  0.053541
1  0.889159  0.459369  0.234851
2  0.463233  0.018573  0.085391
3  0.751360  0.778592  0.258830
4  0.562487  0.522467  0.277639

In [58]:
df - df.mean()

0         1         2
0  0.142728  0.438791 -0.128509
1  0.186917 -0.095079  0.052801
2 -0.239009 -0.535875 -0.096660
3  0.049119  0.224144  0.076779
4 -0.139754 -0.031981  0.095588

In [59]:
df.sub(df.mean(axis=1), axis=0)

0         1         2
0  0.214386  0.362656 -0.577042
1  0.361366 -0.068424 -0.292942
2  0.274167 -0.170493 -0.103675
3  0.155100  0.182331 -0.337431
4  0.108290  0.068269 -0.176559

3. 承上題，請問：

In [72]:
df

0         1         2
0  0.844970  0.993239  0.053541
1  0.889159  0.459369  0.234851
2  0.463233  0.018573  0.085391
3  0.751360  0.778592  0.258830
4  0.562487  0.522467  0.277639

In [66]:
# row sum
dfrow=df.sum(axis=1)
dfrow

0    1.891750
1    1.583379
2    0.567196
3    1.788782
4    1.362593
dtype: float64

In [74]:
dfrow.idxmin()

2

In [73]:
# column sum
df.sum().idxmin()

2

In [76]:
column=df.sum(axis=0)
column

0    3.511209
1    2.772239
2    0.910252
dtype: float64

In [79]:
column.idxmin()

2